#!/bin/bash
syntax="/path/to/MegaFun/buildAnno/MegaFun_anno_pipeline.sh \n\t-param [parameter settings to build annotation for Megafun, see an example in params.txt]"

while [[ $# -gt 1 ]]
do
key="$1"

case $key in

    -param|--parameter) 
    paramfile=$2
    shift
    ;;

    *)

esac
shift
done


if [[ -z "$paramfile" ]]; then
   echo ""
   echo "Usage:"
   echo -e $syntax
   echo ""
   echo "ERROR: no parameter file provided !"
   echo ""
   exit
fi




source $paramfile

if [[ ${runMetaPhlan} == "YES" ]]; then
    # step1: species generated by metaphlan
    if [[ ! -d ${metaphlan_outpath} ]]; then
        mkdir ${metaphlan_outpath}
    fi

    for FILE in `ls -d ${sample_Dir}/*.${suffix_sample}`; do
        prefix=`basename ${FILE} | cut -d. -f1`
        echo ${FILE}
        echo ${prefix}
        echo ${metaphlan_outpath}/${prefix}_profile

        #metaphlan only works with uncompressed data or bam
        inputUnzipFn="./"${prefix}.${file_type}
        if [[ ! -f $inputUnzipFn ]]; then
            gzip -cd ${FILE} > $inputUnzipFn
        fi
        metaphlan --input_type ${file_type} --nproc ${ncore} $inputUnzipFn  ${metaphlan_outpath}/${prefix}_profile.txt > ${metaphlan_outpath}/${prefix}_profile.log 2>&1 # if the input is FASTQ file, then change --input_type into "fastq"
        echo -e "\n"
        #clean up
        rm $inputUnzipFn
        rm *.bowtie2out.txt
    done
    echo "Metaphlan to identify species: Done!"
fi

# extract output of metaphlan to get the list of species
echo "Parse the output of metaphlan to get the species list"
Rscript /path/to/MegaFun/buildAnno/extractSpeciesFromMetaphlan.R in=$metaphlan_outpath p=$metaphlan_prop out=$metaphlan_outpath

bash /path/to/MegaFun/buildAnno/MegaFun_buildAnno.sh -in $metaphlan_outpath/metaphlan_identified_species.txt -out $anno_outpath  -pan $chocoPath  -map $chocoMap -taxname $ncbi_name -taxdb $ncbiSummary -thread $ncore
