#!bin/bash

syntax="/path/to/MegaFun/buildAnno/runMetaphlan.sh \n\t-in [input folder of data sample]  \n\t-out [output folder of metaphlan]  \n\t-suffix [suffix of input sample - gz] \n\t-type [file type (metaphlan): fasta, fastq] \n\t-thread [number of thread] "

while [[ $# -gt 1 ]]
do
key="$1"

case $key in

    -in|--input) 
    sample_Dir=$2
    shift
    ;;

    -out|--ouput) 
    metaphlan_outpath=$2
    shift
    ;;  

    -suffix|--suffix) 
    suffix_sample=$2
    shift
    ;;

    -type|--filetype) 
    file_type=$2
    shift
    ;; 

    -p|--thread) 
    ncore=$2
    shift
    ;; 

    *)

esac
shift
done


if [[ -z "$sample_Dir" ]]; then
   echo ""
   echo "Usage:"
   echo -e $syntax
   echo ""
   echo "ERROR: no input folder provided !"
   echo ""
   exit
fi


if [[ -z "$metaphlan_outpath" ]]; then
   anno_outpath=$PWD
   echo "No specific output folder of metaphlan provided, the output will be save to the current folder!"
fi


if [[ -z "$suffix" ]]; then
   echo ""
   echo "Usage:"
   echo -e $syntax
   echo ""
   echo "ERROR: no suffix of input sample provided !"
   echo ""
   exit
fi


if [[ -z "$file_type" ]]; then
   echo ""
   echo "Usage:"
   echo -e $syntax
   echo ""
   echo "ERROR: no file type (fasta, fastq) provided !"
   echo ""
   exit
fi


if [[ -z "$ncore" ]]; then
   ncore=8
   echo "No specific setting for thread number, so use the default setting (-p 8)"
fi


###################



# step1: species generated by metaphlan

if [[ ! -d ${metaphlan_outpath} ]]; then
    mkdir ${metaphlan_outpath}
fi

for FILE in `ls -d ${sample_Dir}/*.${suffix_sample}`; do
    prefix=`basename ${FILE} | cut -d. -f1`
    echo ${FILE}
    echo ${prefix}
    echo ${metaphlan_outpath}/${prefix}_profile

    #metaphlan only works with uncompressed data or bam
    inputUnzipFn="./"${prefix}.${file_type}
    if [[ ! -f $inputUnzipFn ]]; then
        gzip -cd ${FILE} > $inputUnzipFn
    fi
    metaphlan --input_type ${file_type} --nproc ${ncore} $inputUnzipFn  ${metaphlan_outpath}/${prefix}_profile.txt > ${metaphlan_outpath}/${prefix}_profile.log 2>&1 # if the input is FASTQ file, then change --input_type into "fastq"
    echo -e "\n"
    #clean up
    rm $inputUnzipFn
    rm *.bowtie2out.txt
done
echo "Metaphlan to identify species: Done!"


# extract output of metaphlan to get the list of species
echo "Parse the output of metaphlan to get the species list"
Rscript /path/to/MegaFun/buildAnno/extractSpeciesFromMetaphlan.R in=$metaphlan_outpath p=0.5 out=$metaphlan_outpath
